FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5241

ENV ASPNETCORE_URLS=http://+:5241

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/Clean.Architecture/Clean.Architecture.csproj", "src/Clean.Architecture/"]
RUN dotnet restore "src/Clean.Architecture/Clean.Architecture.csproj"
COPY . .
WORKDIR "/src/src/Clean.Architecture"
RUN dotnet build "Clean.Architecture.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "Clean.Architecture.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Clean.Architecture.dll"]
