FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5241

ENV ASPNETCORE_URLS=http://+:5241

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/CleanArchitecture/CleanArchitecture.csproj", "src/CleanArchitecture/"]
RUN dotnet restore "src/CleanArchitecture/CleanArchitecture.csproj"
COPY . .
WORKDIR "/src/src/CleanArchitecture"
RUN dotnet build "CleanArchitecture.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "CleanArchitecture.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CleanArchitecture.dll"]
