# This workflow will build a .NET project with xUnit tests
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CleanArchitecture

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0
      - name: Restore dependencies
        run: dotnet restore CleanArchitecture.sln
      - name: Build
        run: dotnet build CleanArchitecture.sln --no-restore
      - name: Test
        run: dotnet test CleanArchitecture.sln --no-build --verbosity normal
